### ISSUE TITLE
Compiling instructions

### ISSUE THREAD

**Issue by electro-logic** [mihaibujanca/dynamicfusion#19]
Instructions in README.MD are very little detailed. Attached my compiling instructions tested with Ubuntu 16.04:

[Compiling on Ubuntu 16.04.txt](https://github.com/mihaibujanca/dynamicfusion/files/1279054/Compiling.on.Ubuntu.16.04.txt)

NOTES: See later comment for updated instruction

Compiling with Ubuntu 17.04 require some modifications like:
- Installing GCC 5, VTK 6 and adding "set (CMAKE_CXX_STANDARD 11)" to some CMakeLists.txt

**Comment by mihaibujanca** [comment]
Thanks very much @electro-logic will update the documentation and the cmake file as per your suggestions. Some of those things can be done better indeed (e.g detecting the version of CUDA and only enabling supported architectures)

**Comment by GloriaBian** [comment]
What's the mLibCore.h? When I compile, it shows:
dynamicfusion-master/kfusion/include/opt/mLibInclude.h:15:22: fatal error: mLibCore.h: No such file or directory
 #include <mLibCore.h>
                      ^
compilation terminated.
make[2]: *** [kfusion/CMakeFiles/kfusion.dir/src/precomp.cpp.o] Error 1
make[1]: *** [kfusion/CMakeFiles/kfusion.dir/all] Error 2
make: *** [all] Error 2
Could you tell me how to solve this problem? Thanks!

**Comment by swarth100** [comment]
`mLibCore.h` is included within the [Opt Library](https://github.com/niessner/Opt).

You might want to change the following lines in [CMakeList.txt](https://github.com/mihaibujanca/dynamicfusion/blob/master/CMakeLists.txt#L70) to the paths to your local installation of Opt.

**Comment by electro-logic** [comment]
Here updated instructions for compiling with Opt solver:

[Compiling on Ubuntu 16.04.txt](https://github.com/mihaibujanca/dynamicfusion/files/1524421/Compiling.on.Ubuntu.16.04.txt)

Code compile but I get linking errors:

`[ 77%] Built target kfusion
[ 88%] Built target dynamicfusion
[ 94%] Linking CXX executable ../bin/dynamicfusion_kinect
CMakeFiles/dynamicfusion_kinect.dir/dynamicfusion_kinect.cpp.o: In function `KinFuApp::execute()':
dynamicfusion_kinect.cpp:(.text._ZN8KinFuApp7executeEv[_ZN8KinFuApp7executeEv]+0x177): undefined reference to `kfusion::SampledScopeTime::SampledScopeTime(double&)'
dynamicfusion_kinect.cpp:(.text._ZN8KinFuApp7executeEv[_ZN8KinFuApp7executeEv]+0x1d1): undefined reference to `kfusion::SampledScopeTime::~SampledScopeTime()'
dynamicfusion_kinect.cpp:(.text._ZN8KinFuApp7executeEv[_ZN8KinFuApp7executeEv]+0x4a8): undefined reference to `kfusion::SampledScopeTime::~SampledScopeTime()'
collect2: error: ld returned 1 exit status
apps/CMakeFiles/dynamicfusion_kinect.dir/build.make:126: recipe for target 'bin/dynamicfusion_kinect' failed
make[2]: *** [bin/dynamicfusion_kinect] Error 1
CMakeFiles/Makefile2:179: recipe for target 'apps/CMakeFiles/dynamicfusion_kinect.dir/all' failed
make[1]: *** [apps/CMakeFiles/dynamicfusion_kinect.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

Anyone know how to fix?

**Comment by mihaibujanca** [comment]
Fixed now - linking errors should be gone, but it's not fast enough yet to work in real time, so wouldn't recommend using `dynamicfusion_kinect`

**Comment by electro-logic** [comment]
Now compile and link but program display first frame then terminate with message:

`llvm: No such file or directory`

**Comment by mihaibujanca** [comment]
Are you using it on the dataset or with a kinect?

**Comment by electro-logic** [comment]
Thank you @mihaibujanca as always, I can not test soon the fix but I will do it before Christmas.

**Comment by mihaibujanca** [comment]
No worries, thanks a lot for the contributions

**Comment by Smallha61109** [comment]
Hello everyone, i'm building this project with the instruction from @electro-logic. I've solved the missing mLibCore.h issue with the instruction. However, I encountered with this error: 
```
/home/mml-taitanx/library/Opt/examples/shared/CudaArray.h:19:62: error: there are no arguments to ‘min’ that depend on a template parameter, so a declaration of ‘min’ must be available [-fpermissive] 
cudaSafeCall(cudaMemcpy(cpuBuffer, m_data, sizeof(T)*min(count,m_size), cudaMemcpyDeviceToHost));
```
Do anyone know what I'm doing wrong?

**Comment by mihaibujanca** [comment]
I'm guessing it might have to do with the cuda version or the way you are linking cuda when building Opt

**Comment by mihaibujanca** [comment]
Edit: I have just tried recompiling and am running into the same error. I am pretty sure I haven't modified anything that would cause this but will try to assess it and open an issue to Opt if needed

**Comment by mihaibujanca** [comment]
@Smallha61109 solved by changing min to std::min. I'll submit a PR to Opt but until then I suggest changing it yourself

**Comment by Smallha61109** [comment]
Hi @mihaibujanca , thank you very much!!

**Comment by mihaibujanca** [comment]
@electro-logic I think it should be decent now (at least for Linux, I still didn't get around to do much on the Windows side)

**Comment by electro-logic** [comment]
Sorry for the delay, I have just tried with a new checkout from master but I get same error
`llvm: No such file or directory`

**Comment by mihaibujanca** [comment]
@electro-logic obviously should have documented it when it happened to me :( 

I'll try to reproduce it, but in the meanwhile I'd suggest opening a separate issue for it as this one is about compiling instructions

**Comment by wine3603** [comment]
hello @mihaibujanca 
I am compiling this project today, and got 100%  use
`make -j12`
with this error:
`collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
apps/CMakeFiles/dynamicfusion_kinect.dir/build.make:123: recipe for target 'bin/dynamicfusion_kinect' failed
make[2]: *** [bin/dynamicfusion_kinect] Error 1
apps/CMakeFiles/dynamicfusion.dir/build.make:125: recipe for target 'bin/dynamicfusion' failed
make[2]: *** [bin/dynamicfusion] Error 1
CMakeFiles/Makefile2:147: recipe for target 'apps/CMakeFiles/dynamicfusion_kinect.dir/all' failed
make[1]: *** [apps/CMakeFiles/dynamicfusion_kinect.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:184: recipe for target 'apps/CMakeFiles/dynamicfusion.dir/all' failed
make[1]: *** [apps/CMakeFiles/dynamicfusion.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`
any helps ?
