### ISSUE TITLE
Question about line381 in kinfu.cpp

### ISSUE THREAD

**Issue by mxgbs** [mihaibujanca/dynamicfusion#21]
The 381 line is as following,
getWarp().energy_data(warped, warped_normals, warped, warped_normals);
I assume the input should match following canonical model and live model. But the sentence above looks like that you input the same data set twice. Did I miss something? Could you please advice?

void WarpField::energy_data(const std::vector<Vec3f> &canonical_vertices,
                             const std::vector<Vec3f> &canonical_normals,
                             const std::vector<Vec3f> &live_vertices,
                             const std::vector<Vec3f> &live_normals

**Comment by mihaibujanca** [comment]
Good catch, I should have added a comment at least or not get that into master.

I think at that time I was just using that as a test for the optimisation (obviously it was supposed to converge really quickly and say that the data is identical so no change needs to be made to the warp field.

I'm currently working on a new, GPU-based version which I'm hoping I can get in a good state by early next week or so and will update a couple of other things as well - so thanks for the note :)

**Comment by mihaibujanca** [comment]
This is fixed now
