### ISSUE TITLE
A question about WarpField::init

### ISSUE THREAD

**Issue by fweinan123** [mihaibujanca/dynamicfusion#22]
Hello Mihai,
      I have read your project but I am fused about the WarpField::init in the warp_field.cpp line 79. I want to figure out why you  initialize node's transformation using the PointCloud's point and its normal.
      In my view,  WarpField::init should initialize the estimation of canonical_vertices to live_vertices, so the rotation matrix should be identity matrix and the translation matrix should be zeros. Did I get it wrong?

**Comment by mihaibujanca** [comment]
I think you're right, not entirely sure why I did that - thanks for pointing it out!
I'll update it accordingly.

**Comment by mihaibujanca** [comment]
Sorry, I just realised why I was doing that and it was right. The idea is that you start with the transformation to be the same as the vertices and then it starts deforming. You could also just start with 0 and then use node position + the translation part of the transformation
