### ISSUE TITLE
Why libOpenMeshCore.a cannot be linked to project dynamicfusion?

### ISSUE THREAD

**Issue by HaoguangHuang** [mihaibujanca/dynamicfusion#32]
After changing the variable "OPENMESH_LIBRARIES"  in CMakeLists.txt from author's absolute path into mine, I meet some questions when I complie the project. Here I paste my errors as below:
----------------------------------------------------------------------------------------------------------------------------------------
[ 87%] Built target kfusion
make[3]: *** No rule to make target '/home/hhg/Documents/myGithub2/OpenMesh-6.3/build/Build/lib/libOpenMeshCore.a', needed by 'bin/dynamicfusiond'.  Stop.
CMakeFiles/Makefile2:211: recipe for target 'apps/CMakeFiles/dynamicfusion.dir/all' failed
make[2]: *** [apps/CMakeFiles/dynamicfusion.dir/all] Error 2
CMakeFiles/Makefile2:223: recipe for target 'apps/CMakeFiles/dynamicfusion.dir/rule' failed
make[1]: *** [apps/CMakeFiles/dynamicfusion.dir/rule] Error 2
Makefile:201: recipe for target 'dynamicfusion' failed
make: *** [dynamicfusion] Error 2

Can anyone give me a help? Thanks a lot! @mihaibujanca

**Comment by mihaibujanca** [comment]
Hmm, have you made any other changes to `CMakeLists.txt`? Not really sure how to help here

**Comment by HaoguangHuang** [comment]
I just modify the CMakeLists.txt in directory 'dynamicfusion' like this:

#set(OPT_INCLUDE_DIRS /home/mihai/Projects/Opt/examples/external/mLib/include /home/mihai/Projects/Opt/examples/shared/ /home/mihai/Projects/Opt/API/release/include)
#set(OPT_LIBRARIES /home/mihai/Projects/Opt/API/release/lib/libOptDev.a)
#set(TERRA_LIBRARIES /home/mihai/Projects/terra/lib/libterra.a)
#set(OPENMESH_LIBRARIES /home/mihai/Downloads/OpenMesh-6.3/build/Build/lib/libOpenMeshCore.a /home/mihai/Downloads/OpenMesh-6.3/build/Build/lib/libOpenMeshTools.a)

set(OPT_INCLUDE_DIRS /home/hhg/Documents/myGithub2/Optlang/Opt/examples/external/mLib/include /home/hhg/Documents/myGithub2/Optlang/Opt/examples/shared/ /home/hhg/Documents/myGithub2/Optlang/Opt/API/release/include)
set(OPT_LIBRARIES /home/hhg/Documents/myGithub2/Optlang/Opt/API/release/lib/libOptDev.a)
set(TERRA_LIBRARIES /home/hhg/Documents/myGithub2/Optlang/terra/lib/libterra.a)
set(OPENMESH_LIBRARIES /home/hhg/Documents/myGithub2/OpenMesh-6.3/build/Build/lib/libOpenMeshCore.a /home/hhg/Documents/myGithub2/OpenMesh-6.3/build/Build/lib/libOpenMeshTools.a)
--------------------------------------------------------------------------------------------------------------------------------
It can be assured that the added absolute paths are right after my check. However, the question I asked still exists.

**Comment by HaoguangHuang** [comment]
The issue got solved now.
 
After setting the  variable OPENMESH_LIBRARIES as "OpenMesh-6.3/build/src/OpenMesh/Core/libOpenMeshCored.a  OpenMesh-6.3/build/src/OpenMesh/Tools/libOpenMeshToolsd.a", the error disappeared.
