### ISSUE TITLE
KinFu2 error: invaild device function

### ISSUE THREAD

**Issue by chenkl1995** [mihaibujanca/dynamicfusion#55]
Hi! I rebuild this project on Ubuntu 16.04 with GTX1080.
It could build successfully, but when running it the console shows:
![2018-05-08 20-33-02](https://user-images.githubusercontent.com/15438055/39757346-238697dc-52ff-11e8-887d-d103fe4d3935.png)

Could you give me some suggestions to solve this problem?

Thanks!

**Comment by mihaibujanca** [comment]
Hey there.
What version of CUDA are you using? Can you try running any CUDA demos to make sure you GPU and CUDA is set up correctly?

**Comment by chenkl1995** [comment]
Hi! Thank you for your reply!
I have solved this problem, just comment the CMakeList.txt
    
    64 #if(CUDA_VERSION GREATER 7.5)
    65    list(APPEND CUDA_NVCC_FLAGS "-gencode;arch=compute_61,code=sm_61")
    66 #endif()
Because the `Compute Capability` of `GTX1080` is `6.1`, i guess the `if statement` seems not work properly, after I comment it the program just works.

**Comment by mihaibujanca** [comment]
Hmm, thanks.
Looks like caffe addresses the issue using this code
https://github.com/BVLC/caffe/blob/6eae122a8eb84f8371dde815986cd7524fc4cbaa/cmake/Cuda.cmake#L9-L132
I'll test it soon and add it in
