### ISSUE TITLE
KinFu2 error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by jiwonmoon** [mihaibujanca/dynamicfusion#68]
I execute the dynamicfusion. but, it has an error.

----------------------------------------------------------------------------------------------
$ ./build/bin/dynamicfusion data/umbrella

KinFu2 error: no kernel image is available for execution on the device	/home/jiwon/jiwon/dynamicfusion/kfusion/src/cuda/tsdf_volume.cu:40
----------------------------------------------------------------------------------------------

this is error message. 

and i do this twice in computers the first one is gpu(mx150) and another is gpu(1080) 

and in the /tsdf_volume.cu:40.
the error line is 

----------------------------------------------------------------------------------------------
cudaSafeCall ( cudaGetLastError () );
----------------------------------------------------------------------------------------------

**Comment by mihaibujanca** [comment]
Hi
"no kernel image is available for execution on the device" usually happens when either NVIDIA drivers don't work or when the compute architecture doesn't match the cuda version.


Could you please specify your cuda version, whether or not you can run the cuda examples or any cuda code?

**Comment by jiwonmoon** [comment]
Hi.
thank you 
i solve the problem
 
to use cuda 8.0
and opencv 2.4 version
 
thank you!
 
-----Original Message-----

**Comment by remmel** [comment]
Check your NVidia card compute capability in https://en.m.wikipedia.org/wiki/CUDA#GPUs_supported and make sure that it is in https://github.com/mihaibujanca/dynamicfusion/blob/b687a8987b77c9f613ed072726729d8ce05a458a/CMakeLists.txt#L63
eg my RTX3060 is compute capability 8.6
