### ISSUE TITLE
hi i have another question...

### ISSUE THREAD

**Issue by jiwonmoon** [mihaibujanca/dynamicfusion#69]
![image](https://user-images.githubusercontent.com/41610616/48298904-7b8ae780-e508-11e8-8622-9d49aec9ae64.png)

i can run dynamicfusion code by using given data set. (umbrella 640, 480)

but, it does not work in another file. i input the ballet dataset (1024, 768)
![image](https://user-images.githubusercontent.com/41610616/48298915-bdb42900-e508-11e8-8e08-8e1ca9e8498e.png)

the ballet dataset has same type(png, i convert jpg to png using another image edit tool) but not size.

i also edit the code like that.

[dynamicfusion/kfusion/src/kinfu.cpp]

![image](https://user-images.githubusercontent.com/41610616/48298951-34e9bd00-e509-11e8-8cc8-25b75bce35e2.png)

![image](https://user-images.githubusercontent.com/41610616/48298954-3f0bbb80-e509-11e8-9956-f640a2a935f2.png)

do i change another code in this project?

in summury, 

- i want to input another color, depth data.

- where can i change the code.

thank you !

**Comment by PascalYIN** [comment]
Hello @jiwonmoon ,
I am trying to run this code on my computer and I got the same error as yours, have you finally solved this problem, could you please tell me how did you solve it?
Thank you!
